#!/usr/bin/python3

import argparse
import logging
import sys
from moncic.cli import run
from moncic.ci import LaunchBuild, Bootstrap

log = logging.getLogger(__name__)


def main():
    parser = argparse.ArgumentParser(description="CI tool")
    subparsers = parser.add_subparsers(help="sub-command help", dest="command", required=True)

    LaunchBuild.make_subparser(subparsers)
    Bootstrap.make_subparser(subparsers)

    args = parser.parse_args()
    handler = args.handler(args)
    res = handler.run()
    if res is not None:
        sys.exit(res)


if __name__ == "__main__":
    run(main)
