#!/usr/bin/python3

import argparse
import logging
import moncic
from moncic.cli import run
from moncic import ci


log = logging.getLogger(__name__)


def main():
    parser = argparse.ArgumentParser(description="CI tool")
    parser.add_argument("--version", action="version", version=moncic.__version__)
    subparsers = parser.add_subparsers(help="sub-command help", dest="command", required=True)

    ci.CI.make_subparser(subparsers)
    ci.Images.make_subparser(subparsers)
    ci.Distros.make_subparser(subparsers)
    ci.Bootstrap.make_subparser(subparsers)
    ci.Update.make_subparser(subparsers)
    ci.Remove.make_subparser(subparsers)
    ci.Shell.make_subparser(subparsers)
    ci.Run.make_subparser(subparsers)
    ci.Dedup.make_subparser(subparsers)
    ci.Analyze.make_subparser(subparsers)

    args = parser.parse_args()
    handler = args.command(args)
    return handler.run()


if __name__ == "__main__":
    run(main)
