#!/bin/sh

set -ue

ARGS=""
export PYTHONDEVMODE=1

if [ "$#" -gt 0 ] && [ "$1" = "-v" ]
then
	shift
	ARGS="-v"
fi

if [ "$#" -eq 0 ]
then
	python3 -m unittest discover "$ARGS"
else
	for name in "$@"
	do
		python3 -m unittest discover "$ARGS" -k $name
	done
fi
